trigger:
- main  # Or the branch you want to trigger the pipeline

pool:
  name: localMContainer

jobs:
- job: build
  displayName: 'Build and Deploy Vue.js App'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'  # Specify the Node.js version
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Install dependencies and build'

  - task: ArchiveFiles@2
    inputs:
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/vuejs-app.zip'
          replaceExistingArchive: true
        displayName: 'Archive files'

  - task: CopyFiles@2
    inputs:
      contents: |
        *
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy files to artifact staging directory'
  
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'vuejs-app'
      displayName: 'Publish Artifact'


