trigger:
  - main  # Adjust this to your branch name

pool:
  name: localMContainer

jobs:
  - job: Build
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'  # Specify the Node.js version you need
        displayName: 'Install Node.js'

      - script: |
          npm install
          npm run build
        displayName: 'npm install and build'

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: 'dist'  # The folder containing the files to package
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/vuejs-app.zip'
          replaceExistingArchive: true
        displayName: 'Archive files'

      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)/vuejs-app.zip'
          artifactName: 'vuejs-app'
        displayName: 'Publish Artifact'
