trigger:
  - main  # Adjust this to your branch name

pool:
  name: localMContainer

jobs:
  - job: Build
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '14.x'  # Specify the Node.js version you need
        displayName: 'Install Node.js'

      - script: |
          npm install
          npm run build
        displayName: 'npm install and build'

      # Publish dist folder as artifact
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '/**/dist'  # Specify the path to the dist folder
          artifactName: 'vuejs-app'
        displayName: 'Publish Artifact'
